[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
# base = "light"

# Primary accent color for interactive elements.
# primaryColor = "#A7AAA4"

# Background color for the main content area.
# backgroundColor = "#22262C"


# Background color used for the sidebar and most interactive widgets.
# secondaryBackgroundColor = "4B5563"

# Color used for almost all text.
# textColor = "#EFEDEA"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
# font = "monospace"

base = "light"
primaryColor="#3A9C3B"
backgroundColor="#FAFAFA"
secondaryBackgroundColor="#F2F7F2"
textColor="#31333F"
font="sans serif"

